version: '3.8'

services:
  session-store:
    build: .
    ports:
      - "3008:3008"
    environment:
      - PORT=3008
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=session_store
    depends_on:
      - postgres
    networks:
      - session-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=session_store
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - session-network

volumes:
  postgres-data:

networks:
  session-network: